controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#    TODO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
api_login_check:
    path: /api/login
    methods: [POST]
